---
- name: Install vsftpd
  apt:
    name: vsftpd
    update_cache: yes
    state: present
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install vsftpd
  yum:
    name: vsftpd
    update_cache: yes
    state: present
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Start service
  service:
    name: vsftpd
    state: started
    enabled: yes
